config/routes.rb
Rails.application.routes.draw do
  resources :groups
  devise_for :users
  root 'players#index'

  resources :players do
    collection { post :import}
  end

  resources :locations do
    collection { post :import}
  end

  resources :matches
  resources :home

end

app/models/player.rb
class Player < ActiveRecord::Base
class Player < User
  has_many :playermatches
  has_many :matches, through: :playermatches
  belongs_to :playermatches
  has_many :groups
  belongs_to :groups

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Player.create! row.to_hash
    end
  end
end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/new - via import
  def import
    Player.import(params[:file])
    redirect_to players_path, notice: "Players imported successfully."
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = current_user.players.build(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

############## PRIVATE SECTION
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:first_name, :last_name, :user_name, :password, :photo, :team_name, :role, :gender, :age_category, :skill_level, :record_ind, :record_team, :phone_num, :email, :day_pref1, :time_pref1, :time_pref2, :remember_token, :created_at, :updated_at)
    end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @player.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h4>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :photo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :photo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Group", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :team_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :role, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:role, options_for_select([["Player", "Player"], ["Captain", "Captain"]]), class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Gender", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:gender, options_for_select([["Female", "Female"], ["Male", "Male"]]), {include_blank: true}, class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :age_category, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.select(:age_category, options_for_select([["Adult", "Adult"], ["Senior", "Senior"], ["Under 18", "Under 18"]]), class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :skill_level, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :skill_level, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Phone", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone_num, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Day: 1st Preference", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:day_pref1, options_for_select([["Mon", "Mon"], ["Tue", "Tue"], ["Wed", "Wed"], ["Thu", "Thu"], ["Fri", "Fri"], ["Sat", "Sat"], ["Sun", "Sun"], ["Anyday", "Anyday"]]), {include_blank: true}, class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Time: 1st Preference", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:time_pref1, options_for_select([["Morning", "Morning"], ["Midday", "Midday"], ["Afternoon", "Afternoon"], ["Anytime", "Anytime"]]), {include_blank: true}, class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Day: 2nd Preference", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:day_pref2, options_for_select([["Mon", "Mon"], ["Tue", "Tue"], ["Wed", "Wed"], ["Thu", "Thu"], ["Fri", "Fri"], ["Sat", "Sat"], ["Sun", "Sun"], ["Anyday", "Anyday"]]), {include_blank: true}, class: "form-control") %>
    </div>
  </div>
    <div class="form-group">
    <%= f.label "Time: 2nd Preference", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:time_pref2, options_for_select([["Morning", "Morning"], ["Midday", "Midday"], ["Afternoon", "Afternoon"], ["Anytime", "Anytime"]]), {include_blank: true}, class: "form-control") %>
    </div>
  </div>
  <div class="form-group">
    <!-- <%= f.label :created_at, class: "col-sm-2 control-label" %> -->
    <div class="col-sm-10">
      <%= f.hidden_field :created_at, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <!-- <%= f.label :updated_at, class: "col-sm-2 control-label" %> -->
    <div class="col-sm-10">
      <%= f.hidden_field :updated_at, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="page-header">
  <%= link_to players_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @player, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing player</h1>
</div>

<%= render 'form' %>

app/views/players/index.html.erb
<div class="page-header">
  <%= link_to new_player_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Player
  <% end %>
  <h3>Request Match</h3>
</div>

<div class="table-responsive">
  <table class="table-hover">
    <thead>
      <tr>
            <th></th>
            <th></th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>1st Pref</th>
            <th>2nd Pref</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Text</th>
            <th>Text</th>
            <th>Level</th>
            <th>Team(s)</th>
            <th>Win/Loss</th>


            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @players) do |player| %>
            <td><%= link_to 'Detail', player %></td>
            <td><%= image_tag player.photo, :class => 'thumbs' %></td>
            <td><%= player.first_name %></td>
            <td><%= player.last_name %></td>
            <td><%= player.day_pref1 %> (<%= player.time_pref1 %>)</td>
            <td><%= player.day_pref2 %> (<%= player.time_pref2 %>)</td>
            <td><a href="tel:<%= player.phone_num %>">Call</a></td>
            <td><a href="mailto:<%=player.email%>?subject=Do you want to play tennis on <%=player.day_pref1%> (<%=player.time_pref1%>) or <%=player.day_pref2%> (<%=player.time_pref2%>)?">Email</a></td>
            <td><a href="sms:/ <%= player.phone_num %> /&body=Do you want to play tennis on <%=player.day_pref1%> (<%=player.time_pref1%>) or <%=player.day_pref2%> (<%=player.time_pref2%>)? ">iPhone</a></td>
            <td><a href="sms:/ <%= player.phone_num %> /?body=Do you want to play tennis on <%=player.day_pref1%> (<%=player.time_pref1%>) or <%=player.day_pref2%> (<%=player.time_pref2%>)? ">Android</a></td>
            <td><%= player.skill_level %></td>
            <td><%= player.team_name %></td>
            <td><%= player.record_ind %></td>

            <!-- <td><%= link_to 'Edit', edit_player_path(player) %></td>
            <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure? Deletes cannot be undone.' } %></td> -->
      <% end %>
    </tbody>
  </table>

  <div class = "import">
  <h3>Import Players</h3>
  <%= form_tag import_players_path, multipart: true do %>
      <%= file_field_tag :file %> <br>
      <%= submit_tag "Import" %>
  <% end %>
  </div>

  <br>

</div>

app/views/players/new.html.erb
<div class="page-header">
  <%= link_to players_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h3>New player</h3>
</div>

<%= render 'form' %>

app/views/players/show.html.erb
<div class="page-header">
  <%= link_to players_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_player_path(@player), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <p id="notice"><%= notice %></p>
  <h3>Profile: <strong><%= @player.first_name %> <%= @player.last_name %></strong></h3>
</div>

<dl class="dl-horizontal">

  <dt></dt>
  <dd><%= image_tag @player.photo, :class => 'portrait' %></dd>

  <dt>First name:</dt>
  <dd><%= @player.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @player.last_name %></dd>

  <dt>Phone:</dt>
  <dd><%= @player.phone_num %></dd>

  <dt>Email:</dt>
  <dd><%= @player.email %></dd>

  <dt>1st Preference:</dt>
  <dd><%= @player.day_pref1 %> (<%= @player.time_pref1 %>)</dd>

  <dt>2nd Preference:</dt>
  <dd><%= @player.day_pref2 %> (<%= @player.time_pref2 %>)</dd>

  <dt>Team name:</dt>
  <dd><%= @player.team_name %></dd>

  <dt>Role:</dt>
  <dd><%= @player.role %></dd>

  <dt>Gender:</dt>
  <dd><%= @player.gender %></dd>

  <dt>Age category:</dt>
  <dd><%= @player.age_category %></dd>

  <dt>Skill level:</dt>
  <dd><%= @player.skill_level %></dd>

  <dt>Record ind:</dt>
  <dd><%= @player.record_ind %></dd>

  <dt>Record team:</dt>
  <dd><%= @player.record_team %></dd>



  <dt>Date Created:</dt>
  <dd><%= @player.created_at %></dd>

  <dt>Last Modified:</dt>
  <dd><%= @player.updated_at %></dd>

  <br>

  <dt><strong></strong></dt>
  <dd><span id="destroy_player_profile"><%= link_to 'Delete Profile', @player, method: :delete, data: { confirm: 'Are you sure? This cannot be undone.' } %></span></dd>

</dl>