config/routes.rb
Rails.application.routes.draw do
  resources :groups
  devise_for :users
  root 'players#index'

  resources :players do
    collection { post :import}
  end

  resources :locations do
    collection { post :import}
  end

  resources :matches
  resources :home

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :user
  belongs_to :player
  has_many :playermatches
  has_many :players, through: :playermatches
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = current_user.matches.build
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = current_user.matches.build(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:match_datetime, :match_loc_name, :match_note, :match_opp, :match_outcome, :match_score, :match_loc_address, :created_at, :updated_at)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @match.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h4>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :match_datetime, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :match_datetime, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :match_loc_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :match_loc_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :match_note, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :match_note, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :match_opp, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :match_opp, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :match_outcome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :match_outcome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :match_score, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :match_score, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :match_loc_address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :match_loc_address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :created_at, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :created_at, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :updated_at, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :updated_at, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/matches/edit.html.erb
<div class="page-header">
  <%= link_to matches_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @match, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing match</h1>
</div>

<%= render 'form' %>

app/views/matches/index.html.erb
<div class="page-header">
  <%= link_to new_match_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Match
  <% end %>
  <h3>Group Matches</h3>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
            <th>Date</th>
            <th>Location</th>
            <th>Opponent</th>
            <th>Score</th>
            <th>Win/Loss</th>
            <th>Note</th>
            <th>User Email</th>
            <th></th>
            <th></th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @matches) do |match| %>
            <td><%= match.match_datetime %></td>
            <td><%= match.match_loc_name %></td>
            <td><%= match.match_opp %></td>
            <td><%= match.match_score %></td>
            <td><%= match.match_outcome %></td>
            <td><%= match.match_note %></td>
            <td><%= match.user.email %></td>
            <td><%= link_to 'Details', match %></td>
            <!-- only allow editting and deleting by the user that created the entry -->
            <% if match.user == current_user %>
              <td><%= link_to 'Edit', edit_match_path(match) %></td>
              <td><%= link_to 'Delete', match, method: :delete, data: { confirm: 'Are you sure you want to delete this record?' } %></td>
            <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/matches/new.html.erb
<div class="page-header">
  <%= link_to matches_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New match</h1>
</div>

<%= render 'form' %>

app/views/matches/show.html.erb
<div class="page-header">
  <%= link_to matches_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_match_path(@match), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Match Details:</h1>
</div>

<dl class="dl-horizontal">
  <dt>Date:</dt>
  <dd><%= @match.match_datetime %></dd>

  <dt>Location Name:</dt>
  <dd><%= @match.match_loc_name %></dd>

  <dt>Notes:</dt>
  <dd><%= @match.match_note %></dd>

  <dt>Opponent:</dt>
  <dd><%= @match.match_opp %></dd>

  <dt>Win/Loss?:</dt>
  <dd><%= @match.match_outcome %></dd>

  <dt>Score:</dt>
  <dd><%= @match.match_score %></dd>

  <dt>Match loc address:</dt>
  <dd><%= @match.match_loc_address %></dd>

  <dt>Created:</dt>
  <dd><%= @match.created_at %></dd>

  <dt>Last Modified:</dt>
  <dd><%= @match.updated_at %></dd>

</dl>