config/routes.rb
Rails.application.routes.draw do
  resources :groups
  devise_for :users
  root 'players#index'

  resources :players do
    collection { post :import}
  end

  resources :locations do
    collection { post :import}
  end

  resources :matches
  resources :home

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>TennisGroup</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <img src="/TennisGroup_logo.png" height="40" width="220"><%= link_to "", "locations#index", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

          <!-- <li><a href="home#index">Home</a></li> -->
          <li><%= link_to "Players", players_path %></li>
          <li><%= link_to "Locations", locations_path %></li>
          <li><%= link_to "Matches", matches_path %></li>
          <li><%= link_to "Groups", groups_path %></li>
          <li><a href="                 "></a></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>

        </ul>
      </div>
      <!-- <em> Welcome,  <%= @current_user_email %></em> -->
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
  <div class="notice_alert">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
    <%= yield %>
  </div>
</body>
</html>